spring:
  application:
    name: useR-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/frienduser
    username: root
    password: 123456
  session:
    86400
server:
  port: 8080
  servlet:
    session:
      timeout: 30m
  error:
    include-message: always
    include-binding-errors: always
logging:
  level:
    com.yanshui: DEBUG
    org.apache.ibatis: DEBUG
    com.fasterxml.jackson.databind: INFO
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        logic-delete-type: isDelete
        logic-delete-value: 1
        logic-not-delete-value: 0
