spring:
  application:
    name: useR-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/frienduser
    username: root
    password: 123456
  session:
    86400
server:
  port: 8080
  servlet:
    session:
      timeout: 30m
mybatis-plus:
  configuration:
    global-config:
      db-config:
        logic-delete-type: isDelete
        logic-delete-value: 1
        logic-not-delete-value: 0
