spring:
  application:
    name: useR-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JAWSDB_URL}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 300000
      keepalive-time: 120000
      leak-detection-threshold: 20000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-type: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  servlet:
    session:
      timeout: 86400s
      cookie:
        same-site: None
        secure: true
        http-only: true
  forward-headers-strategy: native

spring:
  session:
    store-type: none
