spring:
  application:
    name: useR-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JAWSDB_URL}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 300000
      keepalive-time: 120000
      leak-detection-threshold: 20000
  session:
    timeout: 86400
